defaults: &defaults
  working_directory: ~/repo
  docker:
    # specify the version you desire here
    - image: circleci/node:8.0


whitelist: &whitelist
  paths:
    - lib/*
    - node_modules/*
    - src/*
    - .eslintrc
    - .npmignore
    - coverage/*
    - LICENSE
    - package-lock.json
    - package.json
    - README.md
    - tsconfig.examples.json
    - tslint.json
    - webpack.config.examples.js
    - webpack.config.js


version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install NPM Packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run Linting
          command: npm run lint
      
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build Typescript Code
          command: npm run build
      
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist
  
  lint_examples:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run Example Linting
          command: npm run lint:examples

  build_examples:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build Example Typescript Code
          command: npm run build:examples

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: NPM Credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: NPM Publish
          command: npm publish


workflows:
  version: 2

  build:
    jobs:
      - checkout:
          filters:
            branches:
              only: /.*/

      - lint:
          requires:
            - checkout
          filters:
            branches:
              only: /.*/

      - build:
          requires:
            - checkout
          filters:
            branches:
              only: /.*/
      
      - lint_examples:
          requires:
            - checkout
          filters:
            branches:
              only: /.*/

      - build_examples:
          requires:
            - checkout
          filters:
            branches:
              only: /.*/

      - publish:
          requires:
            - build
            - lint
            - build_examples
            - lint_examples
          filters:
            branches:
              only: master